### PR TITLE
Add last_active and last_reset values

### PR DESCRIPTION
**Pull request by JamesSwift**
to allow sql statement to complete (no defaults defined).

Pull Request for Issue #1789  
 
#### Testing Instructions

### CODE REVIEW

**Comment by shoulders** [comment]
hi james, i have seeb your issues. i think moat of these aee caused by not having defaults for certain database values. this is on my list of issues for the next release. you can disable strict standards on ubuntu to allow you to install. will do some simple instructions after this next release. next major release will have a new modern template.

**Comment by JamesSwift** [comment]
Hi @shoulders,

Thanks for your reply. Yes, I suspected that was the issue. For me, I'm simply trying to evaluate this software. To get it to work I had to make a few minor fixes, so I thought I'd share them so that while you work on the next version at least the current version won't be broken.

**Comment by shoulders** [comment]
i appreciate the help. a lot of stuff in the backend is getting fixed for this version. my software is easy to use if not that pretty at the moment.

**Comment by shoulders** [comment]
```               register_date       =". $this->app->db->qstr( $this->app->system->general->mysqlDatetime()  ).",  
                last_active         =". $this->app->db->qstr( $this->app->system->general->mysql_datetime()  ).",
                last_reset_time     =". $this->app->db->qstr( $this->app->system->general->mysql_datetime()  ).",
```

- **register_date** is already there
- **last_active** is added when the user does something
- and **last_reset_time** is only used when the password is reset.

But I have now implemented strict DB mode so these fields are now null by default. see #1712

**Pull request closed without merging**
