### PR TITLE
#480 psr2 and psr1 compatibility

### PR DESCRIPTION
**Pull request by valerianpereira**
psr2 and psr1 compatibility.
Partially done. More changes would be provided once this is merged.

### CODE REVIEW

**Comment by shoulders** [comment]
thanks for the update. I will do this for version 3.0.1 because I have just got it stable.  also not all files should be converted. I.e. the libraries.

I can give a list later.

really appreciate  the help.

**Comment by valerianpereira** [comment]
Alright. Do share the list of files later.

**Comment by shoulders** [comment]
@valerianpereira

I have just release QWcrm 3.0.0

I can now look at the PSR1/PSR2 issue before moving forwards. I am new to git so bear with me please.. I have also done loads of commits to the code since you have done these so it might have to delete  the pull request and start again, not 100%

**Comment by valerianpereira** [comment]
@shoulders you may delete the PR.
Will raise another one with the fixes and modify a few files each time to allow you to review and merge it quickly. Sounds fine ?

**Comment by shoulders** [comment]
that sounds great. because i am a github noob, can you update your repo to the latest version and wipe this pull request or is that somthing I have to do.

other than sounds great and will add a list of files to do.

**Pull request closed without merging**
