### PR TITLE
Exception on empty session

### PR DESCRIPTION
**Pull request by JamesSwift**
#### Summary of Changes 
Fixes an error in session handing which prevented a new install from ever working.
 
#### Testing Instructions

### CODE REVIEW

**Comment by shoulders** [comment]
i will look at this one. i am doing gardening while weather is good. i know this can be caused by unset variables causing headers to already been sent error.

**Comment by shoulders** [comment]
I have made some changes to the code supplied

I reworked the code in database.php , i re-examined how the joomla code looked and discovered the issue was still being caused when ```$rs->fields['data']``` was nbot found so i added a ternary operator in here. main thing is if no record is found is to return false which is what the joomla code did via an exception.

The code for insertUser() intentioanlly doe snot have the last_Active time set becasue the user is not active yet. you might create users that are never active but have been created and I needed a flag for this. last_reset_time is for whent he password for the user has beend reset. if it has never been reset it should not have a datetime set. perhaps this is related to the database strict standards I will be implementing.

p.s. still learning how to use Github.

**Comment by mvnaylor** [comment]
This seems to still be an issue. I've been through multiple iterations of attempting to install 3.1.3. I finally got one to work (not sure what changed) and wanted to copy the DB and files to another server but I run into the session issue again. Is there any way around this?

**Comment by shoulders** [comment]
@mvnaylor You can just move files and the database. There is no fixed connection of QWcrm to its current location.

I am just wondering if the fix is in v3.1.4 which is not relesed yet.

What version of PHP are you using?

The code changes I made above in https://github.com/shoulders/qwcrm/commit/ac8f7d320a34ae4de044a038f45e72f5facdcf7e should fix the session error you are having. Backup and give it a go.

**Comment by mvnaylor** [comment]
PHP 7.4
No dice...still dies at the end of the install. Everything seems to be in place, but I cannot ever get to the login page. Trace below.

Whoops\Exception\ErrorException thrown with message "Trying to access array offset on value of type bool"

Stacktrace:
#12 Whoops\Exception\ErrorException in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/joomla/session/storage/database.php:56
#11 Whoops\Run:handleError in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/joomla/session/storage/database.php:56
#10 JSessionStorageDatabase:read in [internal]:0
#9 session_start in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/joomla/session/handler/native.php:261
#8 JSessionHandlerNative:doSessionStart in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/joomla/session/handler/native.php:50
#7 JSessionHandlerNative:start in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/joomla/session/handler/joomla.php:91
#6 JSessionHandlerJoomla:start in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/src/Session/Session.php:675
#5 Joomla\CMS\Session\Session:_start in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/src/Session/Session.php:621
#4 Joomla\CMS\Session\Session:start in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/src/Session/Session.php:499
#3 Joomla\CMS\Session\Session:get in /var/www/html/qwcrm/libraries/qframework/joomla/libraries/src/Session/Session.php:456
#2 Joomla\CMS\Session\Session:isNew in /var/www/html/qwcrm/libraries/qframework/qwcrm/CMSApplication.php:147
#1 CMSApplication:loadSession in /var/www/html/qwcrm/libraries/qframework/qwcrm/CMSApplication.php:66
#0 CMSApplication:execute in /var/www/html/qwcrm/index.php:84

**Comment by shoulders** [comment]
questions
- do you have a working installation of QWcrm but cannot get to work on the new server?
- I have not tested this on PHP 7.4, can you try it on PHP 7.3
- just checking, but when the installation fails, do you make sure the created config file is deleted before you start again?
- can you tell me what your enviroments that you use are, OS, PHP, MySQL version etc...
- the error info above is not enough. I could do with a screenshot of the whoops error rather than just the stack trace.

v3.1.4 has had a lot changed but I wont be able to update QWcrm for a couple of weeks because I have a large project I need to do. I also then will go through and get all of the bugs and stuff done.

**Comment by mvnaylor** [comment]
So, between your patch [ac8f7d3] and James Swift's contribution [https://github.com/shoulders/qwcrm/pull/1792/commits/753d7c0199f7d264202a6a1cf4619a5c18e95f2e] I've managed to install a working version of 3.1.3 on PHP 7.4 / MySQL 8.0.23 / on Ubuntu 20.04.1.

I'm pretty familiar with the install process by this time (not sure how many dozen times I went through it various tweaks) and I think one of my biggest issues was the MySQL mode. By default it is

`ONLY_FULL_GROUP_BY STRICT_TRANS_TABLES NO_ZERO_IN_DATE NO_ZERO_DATE ERROR_FOR_DIVISION_BY_ZERO NO_AUTO_CREATE_USER NO_ENGINE_SUBSTITUTION`

I've now trimmed it down to

`ONLY_FULL_GROUP_BY,​ERROR_FOR_DIVISION_BY_ZERO,​NO_ENGINE_SUBSTITUTION`

as I noticed an issue with zeroes in the first workorder.

I'm willing to try a fresh install when you release 3.1.4 if you like.

**Comment by shoulders** [comment]
see #1712

**Comment by mvnaylor** [comment]
I noticed the STRICT_TRANS_TABLES but my defaults included NO_ZERO_IN_DATE and NO_ZERO_DATE, which caused issues as well. Thanks for the follow up. Love the app so far!

**Pull request closed without merging**
